add rockchip hotfix

diff --git a/hotfix/rockchip_hotfix b/hotfix/rockchip_hotfix
--- a/hotfix/rockchip_hotfix
+++ b/hotfix/rockchip_hotfix
@@ -11,19 +11,17 @@ OK()
 {
     echo -e  "${OK} $1 ${END}"
 }
-
-# if [ ! -e alps ];then
-#     ERROR "Error exec path!!!"
-#     exit 1
-# fi
-if [ ! -e haier ];then
-    ERROR "Error exec path!!!"
+# check if it's in rockchip project
+if [ ! -e RKDocs ];then
+    ERROR "Error path!!!"
     exit 1
 fi
 
-root=$PWD
-# cd alps/system/vold/
-cd haier/system/vold/
+root=$PWD/
+echo "CUR_PATH:"$root
+root=$PWD/../
+echo "root dir:"$root
+cd system/vold/
 branch=`git branch | awk '{if(match($1,"*")){print $2}}'`
 if [ $# != 0 ];then
     RETSUT=`git branch | grep $1`
@@ -45,9 +43,9 @@ if [ $# != 0 ];then
         #   i=${i%/*}/
         #fi
         subfiles=`git diff --name-only $1`
-        echo "######################################################in project $i ######################################################\n">>$DEST/log.txt
+        echo "########################### in project $i ######################\n">>$DEST/log.txt
         git diff $1 >>$DEST/log.txt
-        echo "\n######################################################  END  ######################################################\n">>$DEST/log.txt
+        echo "\n#######################  END  ########################\n">>$DEST/log.txt
 
         for j in $subfiles
         do
@@ -77,19 +75,21 @@ if [ $# != 0 ];then
         cd - >> /dev/null
     done
 else
-    echo "---> cd haier"
-    cd haier
     echo "------->begin"
     echo "------->On branch $branch"
-    `repo status >repo.txt` 
+    echo "------> start get repo status"
+    `repo status >repo.txt`
+    echo "------> get repo status finised"
     project=`awk  '{if(match($1,"project")){print $2}}' repo.txt`
     if [ ! -z "$project" ];then
-        if [ ! -e $root/PATCH/$branch ];then
-            mkdir -p $root/PATCH/$branch
-        fi
         TIME=`date +%Y%m%d%H%M`
+        if [ ! -e $root/PATCH/$branch ];then
+            STAGE_BRACH_FLD=$branch_$TIME
+            mkdir -p $root/PATCH/$branch_$TIME
+        fi
         DEST=Patch_"$TIME"
         mkdir -p $root/PATCH/$branch/$DEST
+        echo "creat path:`$root/PATCH/$branch/$DEST`"
         mv repo.txt $root/PATCH/$branch/$DEST/repo_"$TIME".txt
         for i in $project
         do
@@ -99,9 +99,9 @@ else
             cd $i
             subfiles=`git status -s | awk '{print $NF}'`
             subfiles_nountrack=`git status -s -uno | awk '{print $NF}'`
-            echo "######################################################in project $i ######################################################\n">>$root/PATCH/$branch/$DEST/log_"$TIME".txt
+            echo "#################### in project $i #################\n">>$root/PATCH/$branch/$DEST/log_"$TIME".txt
             git diff >>$root/PATCH/$branch/$DEST/log_"$TIME".txt
-            echo "\n######################################################  END  ######################################################\n">>$root/PATCH/$branch/$DEST/log_"$TIME".txt
+            echo "\n##################  END  #########################\n">>$root/PATCH/$branch/$DEST/log_"$TIME".txt
             for j in $subfiles
             do
                 target=$i$j
@@ -113,20 +113,21 @@ else
 
                 if [ -f  $j ];then
                     cp -rfp $j $root/PATCH/$branch/$DEST/current/$target
-                    echo "out------->PATCH/$branch/$DEST/current/$target"
+                    # echo "out------->PATCH/$branch/$DEST/current/$target"
                 elif [ -d  $j ];then
-                    echo "out------->PATCH/$branch/$DEST/current/$target"
+                    # echo "out------->PATCH/$branch/$DEST/current/$target"
                     target=${target%/*}
                     target=${target%/*}
                     cp  -rfp $j $root/PATCH/$branch/$DEST/current/$target
                 else
                     if [ -e $root/PATCH/$branch/$DEST/current/$target ];then
                         rm $root/PATCH/$branch/$DEST/current/$target
-                        echo "delete------->PATCH/$branch/$DEST/current/$target"
+                        echo "delete -------> PATCH/$branch/$DEST/current/$target"
                     fi
                 fi
             done
             git stash
+            echo "--------------- ready to get changed file before status"
             for j in $subfiles_nountrack
             do
                 target=$i$j
@@ -138,16 +139,16 @@ else
 
                 if [ -f  $j ];then
                     cp -rfp $j $root/PATCH/$branch/$DEST/before/$target
-                    echo "out------->PATCH/$branch/$DEST/before/$target"
+                    # echo "out------->PATCH/$branch/$DEST/before/$target"
                 elif [ -d  $j ];then
-                    echo "out------->PATCH/$branch/$DEST/before/$target"
+                    # echo "out------->PATCH/$branch/$DEST/before/$target"
                     target=${target%/*}
                     target=${target%/*}
                     cp  -rfp $j $root/PATCH/$branch/$DEST/before/$target
                 else
                     if [ -e $root/PATCH/$branch/$DEST/before/$target ];then
                         rm $root/PATCH/$branch/$DEST/before/$target
-                        echo "delete------->PATCH/$branch/$DEST/before/$target"
+                        echo "delete -------> PATCH/$branch/$DEST/before/$target"
                     fi
                 fi
             done
@@ -155,25 +156,25 @@ else
             cd $root
         done
         echo "------->finish"
-        echo "auto commit?(y/n)"
-        read CMD
-        if [ "$CMD" = "y" ];then
-            echo "Comment:"
-            read CONTENT
-            for i in $project
-            do
-                if [ ! -z ${i##*/}  ];then
-                    i=${i%/*}/
-                fi
-                cd $i
-                echo "Project $i"
-                git add --all
-                git commit -am "$CONTENT"
-                cd $root
-            done
-        else
-            exit 1
-        fi
+        # echo "auto commit?(y/n)"
+        # read CMD
+        # if [ "$CMD" = "y" ];then
+        #     echo "Comment:"
+        #     read CONTENT
+        #     for i in $project
+        #     do
+        #         if [ ! -z ${i##*/}  ];then
+        #             i=${i%/*}/
+        #         fi
+        #         cd $i
+        #         echo "Project $i"
+        #         git add --all
+        #         git commit -am "$CONTENT"
+        #         cd $root
+        #     done
+        # else
+        #     exit 1
+        # fi
     else
         echo "nothing to commit (working directory clean)"
     fi
